version: "3"
services:
  stable-diffusor:
    # TODO: exchange this image with an image of CompVis
    image: guestros/stable-diffusion-lstein:latest
    build: .
    platform: linux/amd64
    volumes:
      - ./weights/:/app/weights/
      - ./outputs/:/app/outputs/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]